# Python Knowledge Base
--------------------------------------------------------------
1. Decorator functions
2. NumPy primer
3. The ```*``` idiom


## Decorator Functions
--------------------------------------------------------------
1. Allows modifying the behaviour of a function or class
2. Properties of first class functions:
 - A function is an instance of the Object type.
 - You can store the function in a variable.
 - You can pass the function as a parameter to another function.
 - You can return the function from a function.
 - You can store them in data structures such as hash tables, lists, 

## NumPy Primer
--------------------------------------------------------------
#### Concepts
1. **n-dimensional** array **representation**: ```A [i , j, k]``` - The last element always indicates the **column**, the remaininng then are **groups of rows**. Example: (4, 2, 3) => 3 columns, then 4 "row" bunches, holding 2 "row" bunches. See representation below.
2. **Slicing** syntax: ```[start, end, stride]``` - 'start' and 'end' can be negative. ':' indicates 'all'
3. **Axis**: Simply another name for dimensions. For 2-D array Axis-0 = rows and Axis-1 = columns. 
#### n-dimensional array representation: 
```A [i , j, k]``` - Example: (4, 2, 3) => 3 columns, then 4 "row" bunches, holding 2 "row" bunches
```
[[[35, 20, 12],
  [24,  7, 20]],
  
 [[31, 41, 17],
  [42, 24, 38]],
  
 [[49,  0, 37],
  [46, 18, 15]],

 [[37, 18, 25],
  [42,  4, 10]]]
```

## Decorator Functions

In [19]:
def Add_10(x):
    y=x+10
    return f"Added 10 to {x} = {y}"

def Div_2(x):
    y=x/2.0
    return f"Div {x} by 2 = {y}"

# Decorator functions: Passing the function as an argument
def AorD(funct, n):
    return funct(n)

print(AorD(Add_10, 7))
print(AorD(Div_2, 23))

Added 10 to 7 = 17
Div 23 by 2 = 11.5


## NumPy

### Clipping

In [17]:
import numpy as np

In [18]:
a = np.random.rand(3,2)
print(a)
print('\nClipped: -0.5, 0.5\n') 
ac = np.clip(a, -0.5, 0.5)
print(ac)

[[0.72723332 0.30961377]
 [0.04219065 0.58704908]
 [0.64960359 0.81916769]]

Clipped: -0.5, 0.5

[[0.5        0.30961377]
 [0.04219065 0.5       ]
 [0.5        0.5       ]]


## Deque

In [33]:
from collections import deque
import numpy as np

D = deque(range(s), maxlen=s)
print(D)

for n in range(20):
    C=np.random.choice(D, 3, replace=False)
    print(C)

deque([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], maxlen=10)
[3 1 8]
[9 3 2]
[1 6 8]
[1 2 9]
[2 6 5]
[7 1 9]
[4 0 9]
[6 5 8]
[7 1 0]
[3 1 0]
[9 6 8]
[7 8 3]
[3 6 0]
[7 3 4]
[9 7 6]
[5 8 1]
[6 8 9]
[5 6 4]
[2 6 0]
[9 0 4]


In [17]:
s=10
c = 1
for n in range(100):
    i = c%s
    print(f'c={c:02d}     idx={i:03d}            size={s:03d}')
    c += 1
    if (i==0): print(60*'-')

print(60*'#')

D = deque(range(1, s))
s=10
c = 1
for n in range(100):
    D.append(n)
    i = c%s
    print(f'c={c:02d}     idx={i:03d}            size={s:03d}')
    c += 1
    if (i==0): print(60*'-')


c=01     idx=001            size=010
c=02     idx=002            size=010
c=03     idx=003            size=010
c=04     idx=004            size=010
c=05     idx=005            size=010
c=06     idx=006            size=010
c=07     idx=007            size=010
c=08     idx=008            size=010
c=09     idx=009            size=010
c=10     idx=000            size=010
--------------------
c=11     idx=001            size=010
c=12     idx=002            size=010
c=13     idx=003            size=010
c=14     idx=004            size=010
c=15     idx=005            size=010
c=16     idx=006            size=010
c=17     idx=007            size=010
c=18     idx=008            size=010
c=19     idx=009            size=010
c=20     idx=000            size=010
--------------------
c=21     idx=001            size=010
c=22     idx=002            size=010
c=23     idx=003            size=010
c=24     idx=004            size=010
c=25     idx=005            size=010
c=26     idx=006            size=

### The ```*``` operator  -- "Rest" of list idiom

In [30]:
l = ['a', 'b', 'c', 'd', 'e', 'f', 'g']
k = [0, 1]
lk = [l,k]
print('lk:', lk)

data_1, data_2 = [], []
data_1, data_2 = [*lk]
print('d1 len:', len(data_1), ' d2 len:', len(data_1))
print('data_1: ', data_1) 
print('data_2: ', data_2)

# Star idiom
p = [*l, k]; print(p)
p = [l, *k]; print(p)
p = [*l, *k]; print(p)

(l1, l2, *l3) = p
print(l1) # First element
print(l2) # 2nd  element
print(l3) # remainder of list 

lk: [['a', 'b', 'c', 'd', 'e', 'f', 'g'], [0, 1]]
d1 len: 7  d2 len: 7
data_1:  ['a', 'b', 'c', 'd', 'e', 'f', 'g']
data_2:  [0, 1]
['a', 'b', 'c', 'd', 'e', 'f', 'g', [0, 1]]
[['a', 'b', 'c', 'd', 'e', 'f', 'g'], 0, 1]
['a', 'b', 'c', 'd', 'e', 'f', 'g', 0, 1]
a
b
['c', 'd', 'e', 'f', 'g', 0, 1]


In [8]:
import numpy as np
  
def memory_sizer(mem_size, input_shape):
    
    z = np.zeros((mem_size, *input_shape))
    
    print(f'mem-size: {mem_size}')
    print(f'input size: {input_shape}')
    print(f'Shape of Z: {z.shape}')
    print(30*'-')
    print(z)
    print(60*'=')

In [32]:
print(memory_sizer(3, (2,4)))
print(memory_sizer(3, (2,)))

mem-size: 3
input size: (2, 4)
Shape of Z: (3, 2, 4)
------------------------------
[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
None
mem-size: 3
input size: (2,)
Shape of Z: (3, 2)
------------------------------
[[0. 0.]
 [0. 0.]
 [0. 0.]]
None


In [15]:
A = np.random.randint(low=30, high=200, size=10)
print(A)
batch = np.random.choice(10, 4, replace=False)
print(batch)
print(A[batch])

[119  97  92  89  68 140 169 162 192 100]
[7 2 1 4]
[162  92  97  68]


In [18]:
def add(x, y):
    z = x + y
    return (x,y,z)

print(add(10, 20))

(10, 20, 30)


In [35]:
A = np.random.randint(50, size=(4, 2, 3))
A

array([[[35, 20, 12],
        [24,  7, 20]],

       [[31, 41, 17],
        [42, 24, 38]],

       [[49,  0, 37],
        [46, 18, 15]],

       [[37, 18, 25],
        [42,  4, 10]]])

In [33]:
print(A.shape); print(A); print(60*'-')

B = A[:, -1, 2]; print(B.shape); print(B)

(4, 2, 3)
[[[13 27 41]
  [ 2 49 43]]

 [[44  2 31]
  [14 43  5]]

 [[45 45 36]
  [16 45 17]]

 [[10 12 41]
  [13  9 17]]]
------------------------------------------------------------
(4,)
[43  5 17 17]
